/*
 * Developer: Andrey Zubkov
 * Date: 2015-04-05
 */
var cons = {
    "ABD" : "Abu Dhabi",
    "ABJ" : "Abidjan",
    "ACC" : "Accra",
    "ACK" : "Auckland",
    "AKD" : "Ashgabat",
    "ALG" : "Algiers",
    "AMM" : "Amman",
    "ADD" : "Addis Ababa",
    "AMS" : "Amsterdam",
    "ANK" : "Ankara",
    "ANT" : "Antananarivo",
    "ASM" : "Asmara",
    "ASN" : "Asuncion",
    "ATA" : "Almaty",
    "ATH" : "Athens",
    "BCH" : "Bucharest",
    "BDP" : "Budapest",
    "BEN" : "Bern",
    "BGH" : "Baghdad",
    "BGI" : "Bangui",
    "BGN" : "Bridgetown",
    "BGT" : "Bogota",
    "BLG" : "Belgrade",
    "BLZ" : "Belize City",
    "BMB" : "Bombay",
    "BNK" : "Bangkok",
    "BNS" : "Buenos Aires",
    "BRS" : "Brussels",
    "BRT" : "Beirut",
    "BRZ" : "Brazzaville",
    "BTS" : "Bratislava",
    "BUJ" : "Bujumbura",
    "CDJ" : "Ciudad Juarez",
    "CHS" : "Chisinau",
    "CLM" : "Colombo",
    "COT" : "Cotonou",
    "CPN" : "Copenhagen",
    "CRO" : "Cairo",
    "CRS" : "Caracas",
    "CSB" : "Casablanca",
    "DBL" : "Dublin",
    "DHK" : "Dhaka",
    "DJI" : "Djibouti",
    "DKR" : "Dakar",
    "DMS" : "Damascus",
    "DOH" : "Doha",
    "DRS" : "Dar Es Salaam",
    "FRN" : "Frankfurt",
    "FTN" : "Freetown",
    "GEO" : "Georgetown",
    "GTM" : "Guatemala City",
    "GUZ" : "Guangzhou",
    "GYQ" : "Guayaquil",
    "GZO" : "Guangzhou, China Electronic Processing",
    "HAV" : "Havana",
    "HCM" : "Ho Chi Minh City",
    "HLS" : "Helsinki",
    "HML" : "Hamilton",
    "HNK" : "Hong Kong",
    "HRE" : "Harare",
    "ISL" : "Islamabad",
    "JAK" : "Jakarta",
    "JHN" : "Johannesburg",
    "JRS" : "Jerusalem",
    "KDU" : "Kathmandu",
    "KBL" : "Kabul",
    "KEV" : "Kyiv",
    "KHF" : "Khartoum",
    "KIN" : "Kinshasa",
    "KLL" : "Kuala Lumpur",
    "KNG" : "Kingston",
    "KWT" : "Al Kuwait",
    "LGS" : "Lagos",
    "LIB" : "Libreville",
    "LIL" : "Lilongwe",
    "LJU" : "Ljubljana",
    "LMA" : "Lima",
    "LND" : "London",
    "LOM" : "Lome",
    "LPZ" : "La Paz",
    "LSB" : "Lisbon",
    "LUA" : "Luanda",
    "LUS" : "Lusaka",
    "MEP" : "Ciudad Juarez",
    "MEX" : "Mexico City",
    "MDD" : "Madrid",
    "MDR" : "Madras",
    "MNA" : "Manama",
    "MNG" : "Managua",
    "MNL" : "Manila",
    "MOS" : "Moscow",
    "MRV" : "Monrovia",
    "MST" : "Muscat",
    "MTL" : "Montreal",
    "MTV" : "Montevideo",
    "NCS" : "Nicosia",
    "NHA" : "Naha",
    "NMY" : "Niamey",
    "NPL" : "Naples",
    "NRB" : "Nairobi",
    "NSS" : "Nassau",
    "NWD" : "New Delhi",
    "OSL" : "Oslo",
    "OUG" : "Ouagadougou",
    "PHP" : "Phnom Penh",
    "PIA" : "Praia",
    "PNM" : "Panama City",
    "PRG" : "Prague",
    "PRM" : "Paramaribo",
    "PRS" : "Paris",
    "PTM" : "Port Moresby",
    "PTP" : "Port-au-Prince",
    "PTS" : "Port of Spain",
    "RDJ" : "Rio de Janeiro",
    "RGA" : "Riga",
    "RID" : "Riyadh",
    "RKJ" : "Reykjavik",
    "RNG" : "Rangoon",
    "SAA" : "Sanaa",
    "SAR" : "Sarajevo",
    "SDO" : "Santo Domingo",
    "SEO" : "Seoul",
    "SGP" : "Singapore",
    "SKO" : "Skopje",
    "SNJ" : "San Jose",
    "SNS" : "San Salvador",
    "SNT" : "Santiago",
    "SOF" : "Sofia",
    "STK" : "Stockholm",
    "SUV" : "Suva",
    "SYD" : "Sydney",
    "TAI" : "Taipei",
    "TAL" : "Tallinn",
    "TBL" : "Tbilisi",
    "TGG" : "Tegucigalpa",
    "THT" : "Tashkent",
    "TIA" : "Tirana",
    "TKY" : "Tokyo",
    "TLV" : "Tel Aviv",
    "TNS" : "Tunis",
    "ULN" : "Ulaanbaatar",
    "VNN" : "Vienna",
    "VAC" : "Vancouver",
    "VIL" : "Lithuania",
    "VNT" : "Vientiane",
    "WRW" : "Warsaw",
    "YDE" : "Yaounde",
    "YRV" : "Yerevan",
    "ZGB" : "Zagreb"
}

